const express = require('express');
const router = express.Router();
const { requireAuth } = require('./middleware');
const c = require('../controllers/roomController');
router.get('/', requireAuth, c.list);
router.get('/create', requireAuth, c.getCreate);
router.post('/', requireAuth, c.postCreate);
router.get('/:id/edit', requireAuth, c.getEdit);
router.put('/:id', requireAuth, c.putUpdate);
router.delete('/:id', requireAuth, c.delete);
module.exports = router;
