const express = require('express');
const router = express.Router();
const { requireAuth } = require('./middleware');
const c = require('../controllers/timetableController');
router.get('/', requireAuth, c.index);
router.post('/generate', requireAuth, c.generate);
router.get('/class/:id', requireAuth, c.viewClass);
router.get('/professor/:id', requireAuth, c.viewProfessor);
router.get('/room/:id', requireAuth, c.viewRoom);
router.get('/all-professors', requireAuth, c.allProfessors);
router.get('/all-rooms', requireAuth, c.allRooms);
router.post('/lock-slot', requireAuth, c.lockSlot);
router.delete('/:id', requireAuth, c.delete);
module.exports = router;
