const Class = require('../models/Class');
const Subject = require('../models/Subject');

exports.list = async (req, res) => {
  const classes = await Class.find({ isActive: true }).populate('subjects', 'name code type').sort('year division');
  res.render('classes/index', { title: 'Classes', classes });
};

exports.getCreate = async (req, res) => {
  const subjects = await Subject.find({ isActive: true }).sort('year name');
  res.render('classes/form', { title: 'Add Class', cls: null, subjects, action: '/classes' });
};

exports.postCreate = async (req, res) => {
  try {
    const { year, division, totalStudents, batchCount, subjects } = req.body;
    const subjectIds = Array.isArray(subjects) ? subjects : (subjects ? [subjects] : []);
    const cls = new Class({
      year, division,
      totalStudents: parseInt(totalStudents),
      batchCount: parseInt(batchCount) || 2,
      subjects: subjectIds
    });
    await cls.save();
    req.flash('success', `Class ${year}-${division} created with ${cls.batches.length} batches.`);
    res.redirect('/classes');
  } catch (err) {
    req.flash('error', err.message);
    res.redirect('/classes/create');
  }
};

exports.getEdit = async (req, res) => {
  const [cls, subjects] = await Promise.all([
    Class.findById(req.params.id),
    Subject.find({ isActive: true }).sort('year name')
  ]);
  if (!cls) { req.flash('error', 'Class not found.'); return res.redirect('/classes'); }
  res.render('classes/form', { title: 'Edit Class', cls, subjects, action: `/classes/${cls._id}?_method=PUT` });
};

exports.putUpdate = async (req, res) => {
  try {
    const { year, division, totalStudents, batchCount, subjects } = req.body;
    const subjectIds = Array.isArray(subjects) ? subjects : (subjects ? [subjects] : []);
    const cls = await Class.findById(req.params.id);
    if (!cls) { req.flash('error', 'Class not found.'); return res.redirect('/classes'); }
    cls.year = year;
    cls.division = division;
    cls.totalStudents = parseInt(totalStudents);
    cls.batchCount = parseInt(batchCount) || 2;
    cls.subjects = subjectIds;
    cls.batches = []; // will be regenerated by pre-save hook
    await cls.save();
    req.flash('success', 'Class updated.');
    res.redirect('/classes');
  } catch (err) {
    req.flash('error', err.message);
    res.redirect(`/classes/${req.params.id}/edit`);
  }
};

exports.delete = async (req, res) => {
  await Class.findByIdAndUpdate(req.params.id, { isActive: false });
  req.flash('success', 'Class deleted.');
  res.redirect('/classes');
};
